# _manifests/overlays/dev/appserver-deployment-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1app-appserver-deployment
spec:
  template:
    spec:
      containers:
      - name: appserver
        imagePullPolicy: Never # Força o uso da imagem local no Docker Desktop
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"] # Comando para DEV
        # Adicione aqui um patch para DEBUG_MODE se for necessário
        env:
        - name: DEBUG_MODE
          value: "1" # Força DEBUG=True em desenvolvimento